{{- if .Values.gateway.tls.enabled }}
{{- range .Values.gateway.hostnames }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ . | trimSuffix "." | replace "." "-" | printf "%s-tls" | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: {{ $.Values.gateway.tls.issuer.kind | quote }}
    name: {{ $.Values.gateway.tls.issuer.name | quote }}
  secretName: {{ . | trimSuffix "." | replace "." "-" | printf "%s-tls" | quote }}
  dnsNames:
    - {{ . | quote }}
{{- end }}
{{- end }}
