apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "gateway.labels" $ | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default "cilium" | quote }}
  {{- if .Values.gateway.addresses }}
  addresses:
    {{- range .Values.gateway.addresses }}
    - value: {{ .value | quote }}
      {{- if .type }}
      type: {{ .type | quote }}
      {{- else }}
      type: IPAddress
      {{- end }}
    {{- end }}
  {{- end }}
  listeners:
  {{- range .Values.gateway.hostnames }}
    - protocol: HTTP
      port: 80
      name: {{ . | trimSuffix "." | replace "." "-" | printf "%s-http" | quote }}
      hostname: {{ . | quote }}
      allowedRoutes:
        namespaces:
          from: All
    {{- if $.Values.gateway.tls.enabled }}
    - protocol: HTTPS
      port: 443
      name: {{ . | trimSuffix "." | replace "." "-" | printf "%s-https" | quote }}
      hostname: {{ . | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ include "gateway.secretName" . }}
            namespace: {{ $.Release.Namespace | quote }}
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}
  {{- end }}
  {{- if $.Values.gateway.infrastructure.labels }}
  infrastructure:
    labels:
      {{- toYaml $.Values.gateway.infrastructure.labels | nindent 6 }}
  {{- end }}
