{{- range .Values.issuers }}
{{- if .enabled }}
---
apiVersion: cert-manager.io/v1
kind: {{ .kind | default "Issuer" | quote }}
metadata:
  name: {{ .name | default "letsencrypt-production" | quote }}
  {{- if (eq .kind "Issuer") }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- end }}
  labels:
    {{- include "gateway.labels" $ | nindent 4 }}
spec:
  acme:
    server: {{ .server | quote }}
    privateKeySecretRef:
      name: {{ printf "%s-account-key" .name | quote }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            serviceType: ClusterIP
            parentRefs:
              - kind: Gateway
                namespace: {{ $.Release.Namespace | quote }}
                name: {{ $.Values.gateway.name | default "shared-http" | quote }}
{{- end }}
{{- end }}
