version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci)"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/deploy/tofu"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
    groups:
      terraform:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
    groups:
      gomodules:
        patterns:
          - "*"
  - package-ecosystem: "helm"
    directories:
      - "/charts/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
    groups:
      helm:
        patterns:
          - "*"
