name: herd01
endpoint: https://herd01.nicklasfrahm.dev:6443
nodes:
  controlplanes:
    - name: alpaca
      host: 10.0.20.1
    - name: bison
      host: 10.0.20.2
    - name: camel
      host: 10.0.20.3
  workers:
    - name: deer
      host: 10.0.20.4
