apiVersion: serving.kserve.io/v1alpha1
kind: ClusterStorageContainer
metadata:
  name: hf-hub
spec:
  container:
    name: storage-initializer
    image: kserve/storage-initializer:latest
    env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: hf-secret
            key: HF_TOKEN
            optional: false
    resources:
      requests:
        memory: 6Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: hf://
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen2-instruct
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - "--model_name=qwen2"
      storageUri: "hf://Qwen/Qwen2.5-0.5B-Instruct"
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "2"
          memory: "6Gi"
          nvidia.com/gpu: "1"
# Current error: OOMKilled during download.
