dex:
  enabled: true
  config:
    issuer: "https://auth.nicklasfrahm.dev"
    storage:
      type: memory
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          redirectURI: "https://auth.nicklasfrahm.dev/dex/callback"
          orgs:
            - name: nicklasfrahm-dev
  envVars:
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: dex-github
          key: GITHUB_CLIENT_ID
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dex-github
          key: GITHUB_CLIENT_SECRET

httpRoute:
  enabled: true
  gateway:
    namespace: cloud-system
    name: shared-http
  hostname: "auth.nicklasfrahm.dev"
