dex:
  enabled: true
  config:
    logger:
      level: "warn"
      format: "json"
    issuer: "https://auth.nicklasfrahm.dev"
    storage:
      type: memory
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          redirectURI: "https://auth.nicklasfrahm.dev/callback"
          orgs:
            - name: nicklasfrahm-dev
    staticClients:
      - id: kubernetes
        name: "Kubernetes"
        public: true
        redirectURIs:
          - "http://localhost:8000"
          - "http://localhost:18000"
      - id: argocd
        name: "ArgoCD"
        public: true
        redirectURIs:
          - "https://argocd.cph02.nicklasfrahm.dev/auth/callback"
  envVars:
    # The GitHub OIDC secrets are manually created using:
    # kubectl create secret generic dex-github --from-literal=GITHUB_CLIENT_ID=<client-id> --from-literal=GITHUB_CLIENT_SECRET=<client-secret>
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: dex-github
          key: GITHUB_CLIENT_ID
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dex-github
          key: GITHUB_CLIENT_SECRET

httpRoute:
  enabled: true
  gateway:
    namespace: platform
    name: shared-http
  hostname: "auth.nicklasfrahm.dev"
