# permissions for end users to edit kubernetesclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: kubernetescluster-editor-role
rules:
- apiGroups:
  - cloud.nicklasfrahm.dev
  resources:
  - kubernetesclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.nicklasfrahm.dev
  resources:
  - kubernetesclusters/status
  verbs:
  - get
