apiVersion: v1
kind: Namespace
metadata:
  name: kuard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kuard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuard
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-arm64:3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
  namespace: kuard
spec:
  selector:
    app.kubernetes.io/name: kuard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kuard
  namespace: kuard
spec:
  parentRefs:
    - kind: Gateway
      namespace: kube-system
      name: shared-http
  hostnames:
    - test.cph01.nicklasfrahm.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kuard
          port: 80
