apiVersion: cloud.nicklasfrahm.dev/v1beta1
kind: Machine
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: machine-sample
spec:
  # TODO(user): Add fields here
