{{- if .Values.runtimeClass.enabled }}
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ index .Values "nvidia-device-plugin" "runtimeClassName" | default "nvidia" }}
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
handler: {{ index .Values "nvidia-device-plugin" "runtimeClassName" | default "nvidia" }}
{{- end }}
