{{- if or .Values.global.admins.users .Values.global.admins.groups }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "authz.name" . }}-cluster-admin
  labels:
    {{- include "authz.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
{{- range .Values.global.admins.users }}
  - kind: User
    name: {{ . | quote }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- range .Values.global.admins.groups }}
  - kind: Group
    name: {{ . | quote }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
