{{- if (and (.Values.cilium.gatewayAPI.enabled) (.Values.hooks.gatewayCRDInstaller.enabled)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gateway-crd-installer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
{{- end }}
