wg-easy:
  enabled: true
  image:
    versionOverride: "14"

  # Ensure that we store secrets in a Kubernetes Secret.
  secret:
    create: true

  environmentVariables:
    # WAN IP or a Dynamic DNS hostname.
    WG_HOST: CHANGE_ME
    # Password for the UI.
    PASSWORD: CHANGE_ME
