apiVersion: v2
type: application
name: cilium
description: Deploy the Cilium CNI.
icon: https://artifacthub.io/image/2ae85972-bf12-41a5-afb2-9b1147b2aa56
version: 0.2.1
appVersion: "1.17.5"
dependencies:
  - repository: https://helm.cilium.io/
    name: cilium
    version: 1.17.5
    condition: cilium.enabled
    tags:
      - security
      - networking
      - cni
      - gateway
      - ingress
