kserve:
  enabled: true
  kserve:
    controller:
      deploymentMode: RawDeployment
      gateway:
        ingressGateway:
          enableGatewayApi: true
          kserveGateway: platform/shared-http

kserve-crd:
  enabled: true
