name: Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  pull-requests: write

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.GOOGLE_PROJECT }}
          service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Plan changes
        run: make plan

      - name: Dump plan
        id: dump
        run: |
          {
            echo 'plan<<EOF'
            cat tofu.log
            echo EOF
          } >>"$GITHUB_OUTPUT"

      - name: Find plan comment
        uses: peter-evans/find-comment@v3
        id: find
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "[OpenTofu plan](https://opentofu.org)"

      - name: Publish plan
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚧 [OpenTofu plan](https://opentofu.org) 🚧

            ```txt
            ${{ steps.dump.outputs.plan }}
            ```
          edit-mode: replace

  apply:
    name: Apply
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.GOOGLE_PROJECT }}
          service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Apply changes
        run: make apply
